---
driver:  
  name: vagrant
  require_chef_omnibus: 12.0.1

provisioner:  
  name: chef_zero

platforms:  
  - name: windows-2012r2
    # This line is technically not necessary since TK
    # will auto-detect assuming the beginning of your
    # platform name starts with win
    transport:
        name: winrm
    driver_config:
      customize:
        cpus: 2
        memory: 4096
      box: windows-2012r2-standard
      # THIS IS THE IMPORTANT LINE
      communicator: winrm

      # Helpful for windows testing
      gui: true
  - name: centos-6.5
    driver_config:
      box: opscode-centos-6.5
      customize:
        memory: 512

suites:  
  - name: default
    run_list:
      - recipe[zabbix_windows]
